server:
  port: 8082

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.zhu.model.entity
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video?useUnicode=utf-8&useSSL=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  security:
#    user:
#      password: 123
pig:
  jwt:
    header: Authorization
    expire: 604800
    secret: zhusjd1d48534d5d5d463d1d5d8tge95
